platform :ios, '8.0'
use_frameworks!

workspace 'LazyDemo'
project 'LazyDemoApp/LazyDemoApp.xcodeproj'

target 'LazyDemoApp' do
  pod 'LazyList', :path => '../'

  pod 'XCGLogger'
  pod 'Smile'
  pod 'DeepDiff'
  pod 'Differ'

  pod 'SwiftLint'
  pod 'SwiftFormat/CLI'
end
